#!/usr/bin/env node
/**
 * by Leïlah — static build
 * Copies the root-level site (HTML pages + shared JS/CSS) into dist/.
 * The site is plain static files driven by store.js (localStorage + IndexedDB),
 * so the build is a copy step — no bundler needed.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";

const root = process.cwd();
const out = join(root, "dist");
/* Video assets (hero-video.mp4 etc.) are copied too so the public Hero video
 * is served as a real static asset, accessible to every visitor. */
const EXTENSIONS = new Set([".html", ".js", ".css", ".mp4", ".webm", ".ogv", ".mov", ".m4v"]);
const SKIP = new Set(["dist", "node_modules", ".git", "scripts"]);
const isSiteAsset = (name) =>
  !/\.config\.js$/i.test(name) && !name.startsWith(".") && EXTENSIONS.has(extname(name).toLowerCase());

/* Admin PIN: VITE_ADMIN_PIN (or ADMIN_PIN) is injected into the HTML at build
 * time. When it is unset, the placeholder is emptied and the admin console
 * generates a provisional code on first use (shown on the login screen). */
const PIN_PLACEHOLDER = "%VITE_ADMIN_PIN%";
function resolveAdminPin() {
  const fromEnv = process.env.VITE_ADMIN_PIN || process.env.ADMIN_PIN || "";
  return fromEnv.trim() || "";
}
const adminPin = resolveAdminPin();

if (existsSync(out)) rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

let copied = 0;
for (const name of readdirSync(root)) {
  if (SKIP.has(name)) continue;
  const file = join(root, name);
  if (!statSync(file).isFile()) continue;
  if (!isSiteAsset(name)) continue;
  if (extname(name).toLowerCase() === ".html") {
    const html = readFileSync(file, "utf8").split(PIN_PLACEHOLDER).join(adminPin);
    writeFileSync(join(out, name), html);
  } else {
    cpSync(file, join(out, name));
  }
  copied++;
  console.log("→", name);
}

if (adminPin) console.log(`Admin PIN: injected from environment (VITE_ADMIN_PIN).`);
else console.log("Admin PIN: env var unset — a provisional code is generated on first login in the admin console.");

/* Supabase config for the PUBLIC hero video: regenerated from env vars so the
 * anon key + project URL ship with the deployed site (both are public by
 * design; the anon key is RLS-scoped to the single hero-video object). The
 * value of these keys is never printed. */
const sbUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || "";
const sbKey = process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";
writeFileSync(
  join(out, "supabase-config.js"),
  "/* Generated by scripts/build.mjs — public-by-design Supabase config (anon key). */\n" +
    "window.BL_SUPABASE = { url: " + JSON.stringify(sbUrl) + ", anonKey: " + JSON.stringify(sbKey) + " };\n"
);
if (sbUrl && sbKey) {
  console.log("Supabase config: injected from environment (SUPABASE_URL / SUPABASE_ANON_KEY).");
} else {
  console.log("Supabase config: env vars unset — paste the project URL + anon key in Admin → Réglages → Stockage vidéo, or set SUPABASE_URL / SUPABASE_ANON_KEY and redeploy.");
}

if (!existsSync(join(out, "index.html"))) {
  console.error("Build failed: dist/index.html is missing.");
  process.exit(1);
}
const distAdmin = join(out, "admin.html");
if (existsSync(distAdmin) && readFileSync(distAdmin, "utf8").includes(PIN_PLACEHOLDER)) {
  console.error("Build failed: dist/admin.html still contains the raw %VITE_ADMIN_PIN% placeholder.");
  process.exit(1);
}
console.log(`Build complete — ${copied} file(s) copied to dist/.`);
