#!/usr/bin/env node
/**
 * by Leïlah — static build
 * Copies the root-level site (HTML pages + shared JS/CSS) into dist/.
 * The site is plain static files driven by store.js (localStorage + IndexedDB),
 * so the build is a copy step — no bundler needed.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";

const root = process.cwd();
const out = join(root, "dist");
/* Static media extensions are copied if ever present at the root. The home-hero
 * video is no longer expected here: it lives in Supabase Storage (bucket
 * "byleilah", object hero/home-hero.mp4) and the public URL is derived from
 * supabase-config.js — see the Supabase section in README. */
const EXTENSIONS = new Set([".html", ".js", ".css", ".mp4", ".webm", ".ogv", ".mov", ".m4v"]);
const SKIP = new Set(["dist", "node_modules", ".git", "scripts"]);
const isSiteAsset = (name) =>
  !/\.config\.js$/i.test(name) && !name.startsWith(".") && EXTENSIONS.has(extname(name).toLowerCase());

/* Admin PIN: VITE_ADMIN_PIN (or ADMIN_PIN) is injected into the HTML at build
 * time. When it is unset, the placeholder is emptied and the admin console
 * generates a provisional code on first use (shown on the login screen). */
const PIN_PLACEHOLDER = "%VITE_ADMIN_PIN%";
function resolveAdminPin() {
  const fromEnv = process.env.VITE_ADMIN_PIN || process.env.ADMIN_PIN || "";
  return fromEnv.trim() || "";
}
const adminPin = resolveAdminPin();

if (existsSync(out)) rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });

let copied = 0;
for (const name of readdirSync(root)) {
  if (SKIP.has(name)) continue;
  const file = join(root, name);
  if (!statSync(file).isFile()) continue;
  if (!isSiteAsset(name)) continue;
  if (extname(name).toLowerCase() === ".html") {
    const html = readFileSync(file, "utf8").split(PIN_PLACEHOLDER).join(adminPin);
    writeFileSync(join(out, name), html);
  } else {
    cpSync(file, join(out, name));
  }
  copied++;
  console.log("→", name);
}

if (adminPin) console.log(`Admin PIN: injected from environment (VITE_ADMIN_PIN).`);
else console.log("Admin PIN: env var unset — a provisional code is generated on first login in the admin console.");

/* Supabase config (PUBLIC values — project URL + anon key) for the deployed
 * site. The build regenerates dist/supabase-config.js from SUPABASE_URL /
 * SUPABASE_ANON_KEY (NEXT_PUBLIC_* aliases accepted). When those env vars are
 * unset it falls back to the values checked into the source supabase-config.js
 * so a production build NEVER ships a blank configuration. Both values are
 * public by design (anon key) — their content is never printed. */
function readRootSupabaseConfig() {
  try {
    const code = readFileSync(join(root, "supabase-config.js"), "utf8");
    const mUrl = code.match(/url\s*:\s*"([^"]*)"/);
    const mKey = code.match(/anonKey\s*:\s*"([^"]*)"/);
    return {
      url: mUrl ? mUrl[1].trim() : "",
      anonKey: mKey ? mKey[1].trim() : "",
    };
  } catch {
    return { url: "", anonKey: "" };
  }
}
const rootSb = readRootSupabaseConfig();
const envHasUrl = !!(process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL);
const sbUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || rootSb.url || "";
const sbKey = process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || rootSb.anonKey || "";
writeFileSync(
  join(out, "supabase-config.js"),
  "/* Generated by scripts/build.mjs — public-by-design Supabase config (anon key). */\n" +
    "window.BL_SUPABASE = { url: " + JSON.stringify(sbUrl) + ", anonKey: " + JSON.stringify(sbKey) + " };\n"
);
if (sbUrl && sbKey) {
  console.log(
    envHasUrl
      ? "Supabase config: injected from environment (SUPABASE_URL / SUPABASE_ANON_KEY)."
      : "Supabase config: env vars unset — kept the checked-in public config from supabase-config.js."
  );
} else {
  console.error("Supabase config: no env vars AND no source supabase-config.js values — dist/supabase-config.js would be blank. Set SUPABASE_URL / SUPABASE_ANON_KEY (or fix supabase-config.js) and rebuild.");
  process.exit(1);
}

if (!existsSync(join(out, "index.html"))) {
  console.error("Build failed: dist/index.html is missing.");
  process.exit(1);
}
const distAdmin = join(out, "admin.html");
if (existsSync(distAdmin) && readFileSync(distAdmin, "utf8").includes(PIN_PLACEHOLDER)) {
  console.error("Build failed: dist/admin.html still contains the raw %VITE_ADMIN_PIN% placeholder.");
  process.exit(1);
}
console.log(`Build complete — ${copied} file(s) copied to dist/.`);
